export const FETCH_STASTIC_DATA = 'FETCH_STASTIC_DATA';
export const SUCCESS_STASTIC_DATA = 'SUCCESS_STASTIC_DATA';
export const FAILED_STASTIC_DATA = 'FAILED_STASTIC_DATA';

export const FETCH_MAPS_DATA = 'FETCH_MAPS_DATA';
export const SUCCESS_MAPS_DATA = 'SUCCESS_MAPS_DATA';
export const FAILED_MAPS_DATA = 'FAILED_MAPS_DATA';
