export const FETCH_USER = 'FETCH_USER';
export const SUCCESS_FETCH_USER = 'SUCCESS_FETCH_USER';
export const FAILED_FETCH_USER = 'FAILED_FETCH_ORDERS';

export const FETCH_USER_DETAIL = 'FETCH_USER_DETAIL';
export const SUCCESS_FETCH_USER_DETAIL = 'SUCCESS_FETCH_USER_DETAIL';
export const FAILED_FETCH_USER_DETAIL = 'FAILED_FETCH_USER_DETAIL';

export const SET_USER_SELECTED = 'SET_USER_SELECTED';
export const SET_KEYWORD = 'SET_KEYWORD';
