export const FETCH_ORDERS = 'FETCH_ORDERS';
export const SUCCESS_FETCH_ORDERS = 'SUCCESS_FETCH_ORDERS';
export const FAILED_FETCH_ORDERS = 'FAILED_FETCH_ORDERS';
export const SET_SELECTED_ORDERS = 'SET_SELECTED_ORDERS';

export const FETCH_CREATE_ORDER = 'FETCH_CREATE_ORDER';
export const SUCCESS_CREATE_ORDER = 'SUCCESS_CREATE_ORDER';
export const FAILED_CREATE_ORDER = 'FAILED_CREATE_ORDER';
